version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: bank-postgres
    restart: always
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # сюда положим скрипт создания таблиц и функций

volumes:
  postgres_data: